version: '3'

services:
  zerotier:
    image: stevecliff/zt:latest
    environment:
      - NETWORK_ID=9b............34
      # Example ROUTES below (optional)
      - ROUTES=10.10.12.0/23,10.147.20.115;10.10.14.0/23,10.147.20.220
    volumes:
      - './persistent:/var/lib/zerotier-one'
    network_mode: host
    privileged: true
    restart: always
